### ISSUE TITLE
create POST /api/v1/auth/register route

### ISSUE THREAD

**Issue by emilyparkes** [harakeke-2019/EDAMAME#36]
[Auth](https://github.com/harakeke-2019/jwt-auth)

Create a server/db/users.js that has a createUser db function.
Follow the rest of the instructions linked above.

Update the [wiki](https://github.com/harakeke-2019/EDAMAME/wiki/Server-Routes) accordingly.

**Comment by benlittlenz** [comment]
https://github.com/harakeke-2019/EDAMAME/pull/72
