### ISSUE TITLE
Create dashboard's module view route

### ISSUE THREAD

**Issue by emilyparkes** [harakeke-2019/EDAMAME#61]
This server side route uses a query to determine what content shows on the Student Dashboard Component. 

`/students/:id?view=modules`

In this case, this route will show the module view and related components.
This needs to receive the modules, assessments and exercises for the student dashboard. This relates to #7 & #77.
This information will end up in the store state.

- [ ] Create the route

- [ ] Create db function if needed (joining all three tables)

- [ ] Please update the [wiki](https://github.com/harakeke-2019/EDAMAME/wiki/Server-Routes) with what this shall return when used in postman.

We need to see: 
- evidence
- exercise
- status
- date modified
- assessment title
- student id
- module title
- description

**Comment by jason-simpson** [comment]
We're just so excited to be working on this
