### ISSUE TITLE
ProgressModule component needs 'react-circular-progressbar' dependency to work

### ISSUE THREAD

**Issue by lanelps** [harakeke-2019/EDAMAME#83]
ProgressModule component needs 'react-circular-progressbar' dependency to work.
Need to add 'react-circular-progressbar' as a dependency to package.json.

**Comment by lanelps** [comment]
'react-circular-progressbar' is already in the package.json file.
One other issue was to do with spelling in passing props

**Comment by chrislaupama** [comment]
Fixed.
