### ISSUE TITLE
Create api function to get Assessment Content

### ISSUE THREAD

**Issue by ghost** [harakeke-2019/EDAMAME#86]
Task is to take the information provided in the database on assessments and put it into state so that we can call it onto the browser.
We can currently console.log the information but cant yet bring up in the browser just yet.

**Comment by emilyparkes** [comment]
This api should go to the api route that will receive all assessment content: 

From modules:
the id and title.

From assessments:  
the id and title, description, link and weekday

From exercises:  
the id and title.

- [ ] Write api function

- [ ] Update wiki
